var app = app || {};

app.lessonsJSON = [
  {
    "id": "1",
    "title": "История успеха выпускников ШРИ",
    "videoDownloadUrl": "http://yadi.sk/d/eJU2DcwR99Y7r",
    "videoSize": "677 МБ",
    "pdfDownloadUrl": null,
    "frameVideo": "vnsrv1de6g.4103",
    "framePdf": null,
    "lectorId": "14"
  },
  { "id": "2",
    "title": "Вводная по ШРИ",
    "videoDownloadUrl": "https://disk.yandex.ru/public/?hash=6zN0uNHObhG32y5ZZcEUprIf3sBQYf4kALRQTMnLA5E%3D",
    "videoSize": "217 МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/MLv45rLg9R9NN",
    "frameVideo": "r29oly6fy4.4720",
    "framePdf": "26263315",
    "lectorId": "13"
  },
  { "id": "3",
    "title": "Общий цикл разработки (dev-cycle)",
    "videoDownloadUrl": "http://yadi.sk/d/JxgHuAxS99YDe",
    "videoSize": "1 ГБ",
    "pdfDownloadUrl": "http://yadi.sk/d/nH6dAjFX9R9ct",
    "frameVideo": "u7myq83g9q.4811",
    "framePdf": "26263573",
    "lectorId": "12"
  },
  { "id": "4",
    "title": "Документирование информации",
    "videoDownloadUrl": "http://yadi.sk/d/VrI0by_E99YRQ",
    "videoSize": "808 МБ",
    "pdfDownloadUrl": null,
    "frameVideo": "hlgkkpcf67.3822",
    "framePdf": null,
    "lectorId": "11"
  },
  { "id": "5",
    "title": "Вики-синтаксис",
    "videoDownloadUrl": "http://yadi.sk/d/dcd1Ex1L99YKN",
    "videoSize": "557 МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/XcJgd1oJ9R9WA",
    "frameVideo": "mifh2zd4xw.7143",
    "framePdf": "26263370",
    "lectorId": "11"
  },
  { "id": "6",
    "title": "Cистемы контроля версий",
    "videoDownloadUrl": "http://yadi.sk/d/_BZt0nfx9XwPb",
    "videoSize": "660 МБ",
    "pdfDownloadUrl": null,
    "frameVideo": "oeunffeksq.5100",
    "framePdf": null,
    "lectorId": "10"
  },
  { "id": "7",
    "title": "Тестирование",
    "videoDownloadUrl": "http://yadi.sk/d/pewmgy_z9YFsh",
    "videoSize": "499 МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/B-4RHlxQ9owzn",
    "frameVideo": "u7neb4ukb7.4729",
    "framePdf": "26495249",
    "lectorId": "9"
  },
  { "id": "8",
    "title": "Языки программирования",
    "videoDownloadUrl": "http://yadi.sk/d/m1QrFolf9o43i",
    "videoSize": "384 МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/my2Yax_s9pX7Y",
    "frameVideo": "uery0fxkg2.7247",
    "framePdf": "26501860",
    "lectorId": "8"
  },
  { "id": "9",
    "title": "Архитектура веб-сервисов",
    "videoDownloadUrl": null,
    "videoSize": "МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/r8vD_o5w9phZ6",
    "frameVideo": null,
    "framePdf": "26503527",
    "lectorId": "8"
  },
  { "id": "10",
    "title": "Командная строка Unix",
    "videoDownloadUrl": "http://yadi.sk/d/GbLf_m8W9NMMz",
    "videoSize": "1.3 ГБ",
    "pdfDownloadUrl": "http://yadi.sk/d/hDGgd0Ri9R9hV",
    "frameVideo": "yc39l9dh0a.4723",
    "framePdf": "26263542",
    "lectorId": "7"
  },
  { "id": "11",
    "title": "Регулярные выражения",
    "videoDownloadUrl": "http://yadi.sk/d/AU6yRkm89oATJ",
    "videoSize": "378 МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/5uaBj1Kh9pYRV",
    "frameVideo": "x79ax18q9w.3802",
    "framePdf": "26502148",
    "lectorId": "3"
  },
  { "id": "12",
    "title": "Безопасность веб-приложений",
    "videoDownloadUrl": "http://yadi.sk/d/Py0p5T629mVC4",
    "videoSize": "511 МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/IvhR9B0d9pW9b",
    "frameVideo": "4fcm2v836x.2020",
    "framePdf": "26501715",
    "lectorId": "6"
  },
  { "id": "13",
    "title": "Кеширование на клиенте и сервере",
    "videoDownloadUrl": "http://yadi.sk/d/u5oT64VL9mV7d",
    "videoSize": "614 МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/arbrbY-b9pTMD",
    "frameVideo": "0tk8ubi12b.7216",
    "framePdf": "26501207",
    "lectorId": "5"
  },
  { "id": "14",
    "title": "Механизм работы браузера",
    "videoDownloadUrl": "http://yadi.sk/d/gA1BPlYa9mUrh",
    "videoSize": "430 МБ",
    "pdfDownloadUrl": null,
    "frameVideo": "sg6f9vxh4h.7140",
    "framePdf": null,
    "lectorId": "4"
  },
  { "id": "15",
    "title": "http-протокол",
    "videoDownloadUrl": "http://yadi.sk/d/KYHu9GdH9Xwnz",
    "videoSize": "529 МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/xX6A0UNG9pATV",
    "frameVideo": "w2b30qpu64.4923",
    "framePdf": "26497696",
    "lectorId": "3"
  },
  { "id": "16",
    "title": "Развертывание верстки",
    "videoDownloadUrl": "http://yadi.sk/d/iGfZDEk39XxEj",
    "videoSize": "486 МБ",
    "pdfDownloadUrl": "http://yadi.sk/d/NAt_q4h69p8jq",
    "frameVideo": "gmhj6jhjbq.7339",
    "framePdf": "26497344",
    "lectorId": "2"
  },
  { "id": "17",
    "title": "Изучение и редактирование кода",
    "videoDownloadUrl": "http://yadi.sk/d/2Mb2aQqz9NMcD",
    "videoSize": "1.6 ГБ",
    "pdfDownloadUrl": "http://yadi.sk/d/DllB56WW9R9Zs",
    "frameVideo": "nvby8zm0d8.3121",
    "framePdf": "26263503",
    "lectorId": "1"
  }
];